"use client";
import Link from "next/link";
import {GoogleAuthProvider,linkWithPopup,onAuthStateChanged,signInWithPopup,type User} from "firebase/auth";
import {useEffect,useState} from "react";
import {auth} from "@/lib/firebase/client";
import {getFoodOrder,subscribeToFoodOrder,type FoodOrder} from "@/lib/firebase/data";
import {downloadReceiptPdf} from "@/lib/plug/receipt";
function statusText(status:FoodOrder["status"]){return status==="New"?"Order received":status}
function authMessage(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String((error as {code?:unknown}).code):"";if(code==="auth/popup-closed-by-user")return "Google sign-in was cancelled.";if(code==="auth/popup-blocked")return "Your browser blocked the Google sign-in window. Allow pop-ups for The Plug and try again.";if(code==="auth/account-exists-with-different-credential")return "That Google email already has a The Plug account with another sign-in method. Use the original sign-in method, then connect Google from My The Plug.";if(code==="auth/credential-already-in-use")return "That Google account is already connected to another The Plug account.";if(code==="auth/provider-already-linked")return "Google is already connected to this The Plug account.";return error instanceof Error?error.message:"Google sign-in could not be completed."}
function orderAccessMessage(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String((error as {code?:unknown}).code):"";if(code==="permission-denied"||code==="firestore/permission-denied")return "This order is protected by the customer session that placed it. We can still show the copy saved on this device; live tracking needs that guest session or the connected Google account.";return error instanceof Error?error.message:"We could not load this order."}
function readLocalOrder(id:string):FoodOrder|null{if(typeof window==="undefined")return null;try{const raw=window.localStorage.getItem(`the-plug-order-${id}`);return raw?JSON.parse(raw) as FoodOrder:null}catch{return null}}
export default function OrderTrackingPage({params}:{params:Promise<{id:string}>}){
 const[order,setOrder]=useState<FoodOrder|null>(null),[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[localOnly,setLocalOnly]=useState(false);
 useEffect(()=>{let active=true;let stop=()=>{};const unsubscribe=onAuthStateChanged(auth,next=>{setUser(next);void params.then(async({id})=>{if(!active)return;stop();stop=()=>{};const local=readLocalOrder(id);try{if(!next){if(local){setOrder(local);setLocalOnly(true);setError("This is the copy saved on this device. Live updates need the guest session that placed the order.");}else setError("This order needs the guest session used when it was placed. Open the tracking link on that device/browser, or sign in from My The Plug if that guest session was already connected to Google.");return}const found=await getFoodOrder(id);if(!active)return;if(!found){if(local){setOrder(local);setLocalOnly(true);setError("The live order record is not available right now. This is the private copy saved on this device.");}else setError("That The Plug order could not be found. Check the tracking link or open My The Plug.");return}setOrder(found);setLocalOnly(false);setError("");stop=subscribeToFoodOrder(id,nextOrder=>{if(nextOrder){setOrder(nextOrder);try{window.localStorage.setItem(`the-plug-order-${id}`,JSON.stringify(nextOrder))}catch{}}},err=>{if(local){setOrder(local);setLocalOnly(true);setError(orderAccessMessage(err))}else setError(orderAccessMessage(err))})}catch(err){if(local){setOrder(local);setLocalOnly(true);setError(orderAccessMessage(err))}else setError(orderAccessMessage(err))}finally{if(active)setLoading(false)}})});return()=>{active=false;unsubscribe();stop()}},[params]);
 async function google(){try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});if(user?.isAnonymous)await linkWithPopup(user,provider);else await signInWithPopup(auth,provider);setError("")}catch(err){setError(authMessage(err))}}
 const owns=Boolean(order?.customerId&&user?.uid===order.customerId);
 return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">B</span><span>The Plug</span></Link><Link href="/account" className="button buttonLight">My The Plug</Link></div><section className="orderCard" style={{maxWidth:760,margin:"0 auto"}}>{loading?<div className="emptyState">Loading your order…</div>:error&&!order?<><span className="kicker">The Plug order</span><h1>Order unavailable.</h1><p>{error}</p><p className="orderTruth">Order details stay private. The same-device guest session or connected customer account is required for live order access.</p><Link className="button buttonPrimary" href="/account">Go to My The Plug</Link></>:order?<><span className="kicker">{localOnly?"Saved on this device":"Live order tracking"}</span><h1>#{order.id.slice(0,8).toUpperCase()}</h1>{error&&<p className="notice">{error}</p>}<div className="stats"><article><span>Status</span><strong>{statusText(order.status)}</strong></article><article><span>Total</span><strong>P{order.total.toFixed(2)}</strong></article></div><p>Requested for <strong>{new Date(order.scheduledFor).toLocaleString()}</strong> · {order.mode==="delivery"?"Delivery":"Pickup"}</p>{order.mode==="delivery"&&<p>📍 {order.deliveryLocation}</p>}<section style={{marginTop:24}}><h2>Order progress</h2><div className="queue">{["New","Accepted","Preparing","Ready",order.mode==="delivery"?"Delivering":"Collected",order.mode==="delivery"?"Delivered":"Collected"].filter((v,i,a)=>a.indexOf(v)===i).map(step=><div className="queueRow" key={step}><strong>{step}</strong><span>{step===order.status?"Current":(["New","Accepted","Preparing","Ready","Delivering","Collected","Delivered"].indexOf(step)<["New","Accepted","Preparing","Ready","Delivering","Collected","Delivered"].indexOf(order.status)?"Done":"Waiting")}</span></div>)}</div></section><section style={{marginTop:24}}><h2>Items</h2>{order.items.map(item=><p key={item.name}>{item.quantity} × {item.name} — P{(item.price*item.quantity).toFixed(2)}</p>)}</section><div className="actions"><button className="button buttonPrimary" type="button" onClick={()=>downloadReceiptPdf(order)}>Download PDF receipt</button><button className="button buttonLight" type="button" onClick={()=>window.print()}>Print</button></div>{!owns&&!localOnly&&<div className="notice"><strong>Make this your account.</strong><p>Connect Google from this same guest session to keep the order associated with your The Plug account.</p><button className="button buttonLight" type="button" onClick={()=>void google()}>Continue with Google</button></div>}{localOnly&&<div className="notice"><strong>Saved on this phone.</strong><p>This copy is private to this browser. Reopen it here for the saved order; live kitchen status becomes available when the original guest session is available.</p><Link className="button buttonLight" href="/account">Open My The Plug</Link></div>}</>:null}</section></div></main>;
}
