"use client";
import Link from "next/link";
import StorefrontFeed from "@/components/StorefrontFeed";
import CommunityFeed from "@/components/CommunityFeed";
import {useEffect,useState} from "react";
import {onAuthStateChanged,type User} from "firebase/auth";
import {auth,hasFirebaseWebConfig} from "@/lib/firebase/client";
const WHATSAPP_CATALOG="https://wa.me/c/26776411150", INSTAGRAM="https://www.instagram.com/the.plugworldwidebw/";
function openInstallPrompt(){window.dispatchEvent(new Event("theplug-open-install"));}
export default function Home(){const [member,setMember]=useState<User|null>(null);const [memberChecked,setMemberChecked]=useState(false);const [benefitsOpen,setBenefitsOpen]=useState(false);useEffect(()=>{if(!hasFirebaseWebConfig){setMemberChecked(true);return;}return onAuthStateChanged(auth,user=>{setMember(user);setMemberChecked(true);});},[]);return <main className="plugSite plugEditorialHome">
<div className="plugNotice"><div className="plugContainer"><span>🇧🇼 BOTSWANA</span><strong>If we can source it, you can get it.</strong><span>GABORONE · BW</span></div></div>
<header className="plugNav plugEditorialNav"><div className="plugContainer plugNavInner"><Link href="/" className="plugBrand"><span className="plugMark">P</span><span><strong>THE PLUG</strong><small>SNEAKERS · APPAREL · SOURCING</small></span></Link><nav className="plugEditorialLinks" aria-label="Main navigation"><a href="#featured">Finds</a><a href="#deals">Live offers</a></nav><div className="plugActions"><Link href="/account" className="plugButton plugButtonGhost">My Plug ↗</Link><button type="button" onClick={openInstallPrompt} className="plugButton plugButtonGhost">Install ↓</button></div></div></header>
<StorefrontFeed/><CommunityFeed/>
<section className="plugMemberLoop"><div className="plugContainer"><div className="plugMemberLoopHead"><div><span className="plugKicker">THE PLUG · YOUR SPACE</span><h2>Keep your finds <em>close.</em></h2></div><button type="button" aria-expanded={benefitsOpen} onClick={()=>setBenefitsOpen(open=>!open)} className="plugMemberLoopToggle">{benefitsOpen?"Hide member perks":"See what stays with you"} <span>{benefitsOpen?"−":"＋"}</span></button></div>{benefitsOpen&&<div className="plugMemberPerks"><article><span>01 / YOUR HISTORY</span><h3>Requests, together.</h3><p>Keep your requests, private replies and progress in My Plug.</p></article><article><span>02 / YOUR TIMING</span><h3>Only useful updates.</h3><p>Choose whether to receive relevant notifications when you’re ready.</p></article><article><span>03 / REAL OFFERS</span><h3>No made-up perks.</h3><p>See offers and rewards only when Frank has actually published and confirmed them.</p></article><article><span>04 / KEEP ACCESS</span><h3>Take your history with you.</h3><p>Connect Google to keep access to this session’s history across devices.</p></article><div className="plugMemberPerksAction"><Link href="/account" className="plugCircleAction">Open My Plug <span>↗</span></Link><small>Browsing stays open. Account linking is your choice.</small></div></div>}{memberChecked&&member&&!member.isAnonymous&&<div className="plugMemberUtility"><span>ACCOUNT HOLDER UTILITIES</span><p>Already checked The Plug’s edit? Open the full catalogue or contact Frank directly.</p><div><a href={WHATSAPP_CATALOG} target="_blank" rel="noreferrer">WhatsApp catalogue ↗</a><a href={INSTAGRAM} target="_blank" rel="noreferrer">Instagram ↗</a></div></div>}</div></section>
<footer className="plugFooter plugEditorialFooter"><div className="plugContainer"><strong>THE PLUG</strong><span>SNEAKERS · APPAREL · SOURCING IN BOTSWANA</span><Link href="/account">My Plug</Link><Link href="/request">Request a product</Link>{memberChecked&&member&&!member.isAnonymous&&<><a href={WHATSAPP_CATALOG} target="_blank" rel="noreferrer">WhatsApp catalogue ↗</a><a href={INSTAGRAM} target="_blank" rel="noreferrer">Instagram ↗</a></>}<button type="button" onClick={openInstallPrompt}>Install The Plug ↑</button><Link href="/admin">Admin</Link></div></footer>
</main>}
