"use client";
import {useEffect,useState} from "react";
import {collection,doc,getDoc,getDocs,query,where,writeBatch} from "firebase/firestore";
import type {User} from "firebase/auth";
import {db} from "@/lib/firebase/client";
type ShareScope="private"|"friends"|"public";
export default function MemberPrivacySettings({user,displayName}:{user:User;displayName:string}){
 const[sharePurchases,setSharePurchases]=useState<ShareScope>("private"),[showInCircle,setShowInCircle]=useState(false),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;void getDoc(doc(db,"memberSettings",user.uid)).then(snapshot=>{if(!active)return;if(snapshot.exists()){const data=snapshot.data();if(["private","friends","public"].includes(data.sharePurchases))setSharePurchases(data.sharePurchases as ShareScope);setShowInCircle(data.showInCircle===true)}setLoaded(true)}).catch(()=>{if(active){setMessage("Your privacy settings could not be loaded. Try again before saving.");setLoaded(true)}});return()=>{active=false}},[user.uid]);
 async function save(){if(busy||!loaded)return;setBusy(true);setMessage("");try{const batch=writeBatch(db);const settingsRef=doc(db,"memberSettings",user.uid);batch.set(settingsRef,{uid:user.uid,displayName:displayName.trim().slice(0,60),sharePurchases,showInCircle,updatedAt:new Date().toISOString()});const activity=await getDocs(query(collection(db,"communityActivity"),where("ownerUid","==",user.uid)));for(const item of activity.docs){if(sharePurchases==="private"||item.data().audience!==sharePurchases)batch.delete(item.ref)}await batch.commit();setMessage("Your privacy choices are saved. Posts outside your new sharing choice have been removed.")}catch{setMessage("Your privacy choices were not saved. Nothing was changed; please try again.")}finally{setBusy(false)}}
 return <section className="accountSection memberPrivacy" id="privacy"><div className="panelHeading"><div><span className="kicker">YOU’RE IN CONTROL</span><h2>What do you share?</h2></div></div><p className="orderTruth">Only completed requests marked Delivered or Collected can appear as purchase activity, and Frank must publish the activity. Your phone, messages, delivery details and payment information are never shared.</p><fieldset className="memberPrivacyOptions" disabled={busy||!loaded}><legend>Purchase activity</legend><label><input type="radio" name="sharePurchases" value="private" checked={sharePurchases==="private"} onChange={()=>setSharePurchases("private")}/><span><strong>Private</strong><small>Only you and The Plug can see it.</small></span></label><label><input type="radio" name="sharePurchases" value="friends" checked={sharePurchases==="friends"} onChange={()=>setSharePurchases("friends")}/><span><strong>Friends</strong><small>Only your accepted Plug connections can see published activity.</small></span></label><label><input type="radio" name="sharePurchases" value="public" checked={sharePurchases==="public"} onChange={()=>setSharePurchases("public")}/><span><strong>Public</strong><small>Published completed finds may appear in the community feed.</small></span></label></fieldset><label className="memberDirectoryChoice"><input type="checkbox" checked={showInCircle} disabled={busy||!loaded} onChange={e=>setShowInCircle(e.target.checked)}/><span><strong>Show me in the Plug Circle directory</strong><small>This is optional. Only confirmed members who opt in count toward the visible circle total.</small></span></label><button className="button buttonPrimary" type="button" onClick={()=>void save()} disabled={busy||!loaded}>{!loaded?"Loading privacy…":busy?"Saving choices…":"Save privacy choices"}</button>{message&&<p className="notice" role="status">{message}</p>}</section>
}
