"use client";
import {useEffect,useState} from "react";
import {getIdToken,onAuthStateChanged} from "firebase/auth";
import {getToken,onMessage} from "firebase/messaging";
import {auth} from "@/lib/firebase/client";
import {getNotificationPreferences,isAdminUser,saveNotificationPreferences,saveNotificationToken,type NotificationPreferences} from "@/lib/firebase/data";
import {getMessagingInstance} from "@/lib/firebase/notifications";

const LEAD_OPTIONS=[5,10,15,20,30,45,60];
const FIREBASE_WEB_PUSH_PUBLIC_KEY=process.env.NEXT_PUBLIC_FIREBASE_VAPID_KEY||"";

async function getCurrentDeviceToken(){
 if(!FIREBASE_WEB_PUSH_PUBLIC_KEY)throw new Error("Push notifications are not configured for The Plug yet.");
 const messaging=await getMessagingInstance();
 const registration=await navigator.serviceWorker.ready;
 return getToken(messaging,{vapidKey:FIREBASE_WEB_PUSH_PUBLIC_KEY,serviceWorkerRegistration:registration});
}

export default function NotificationSettings(){
 const[userUid,setUserUid]=useState<string|null>(null),[prefs,setPrefs]=useState<NotificationPreferences>({enabled:false,leadMinutes:15,updatedAt:""}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[admin,setAdmin]=useState(false);
 useEffect(()=>{const unsubscribeAuth=onAuthStateChanged(auth,async user=>{if(!user){setUserUid(null);return}setUserUid(user.uid);try{const [saved,isAdmin]=await Promise.all([getNotificationPreferences(user.uid),isAdminUser(user.uid)]);setPrefs(saved??{enabled:false,leadMinutes:15,updatedAt:""});setAdmin(isAdmin)}catch(error){console.warn("The Plug notification settings unavailable",error)}});return unsubscribeAuth},[]);
 useEffect(()=>{let unsubscribeMessage:undefined|(()=>void);let cancelled=false;void (async()=>{try{if(!userUid||typeof window==="undefined"||!("Notification" in window)||Notification.permission!=="granted")return;const messaging=await getMessagingInstance();if(cancelled)return;unsubscribeMessage=onMessage(messaging,payload=>{const title=payload.notification?.title||"The Plug pickup reminder";const body=payload.notification?.body||"Your The Plug pickup is coming up.";const link=payload.fcmOptions?.link||payload.data?.link||"/account";void navigator.serviceWorker.ready.then(registration=>registration.showNotification(title,{body,icon:"/icon.svg",badge:"/icon.svg",tag:payload.data?.orderId?"boemo-pickup-"+payload.data.orderId:undefined,data:{link}})).catch(error=>console.warn("The Plug foreground notification display unavailable",error))})}catch(error){console.warn("The Plug foreground notifications unavailable",error)}})();return()=>{cancelled=true;unsubscribeMessage?.()}},[userUid]);
 async function enable(){if(!userUid)return;setBusy(true);setMessage("");try{if(!("Notification" in window)||!("serviceWorker" in navigator)){throw new Error("This browser does not support The Plug push notifications.")}const permission=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(permission!=="granted"){setMessage("Notifications are not enabled. You can allow them later in your browser/site settings.");return}const token=await getCurrentDeviceToken();if(!token)throw new Error("The Plug could not register this device for notifications.");await saveNotificationToken(userUid,token,admin);const next={...prefs,enabled:true,updatedAt:new Date().toISOString()};await saveNotificationPreferences(userUid,next);setPrefs(next);setMessage(admin?"Kitchen alerts are on for this device. You will receive new-order and pickup alerts here.":"Pickup reminders are on for this device. The Plug will use your saved reminder time for future orders.")}catch(error){setMessage(error instanceof Error?error.message:"Notifications could not be enabled.")}finally{setBusy(false)}}
 async function testNotification(){if(!userUid)return;setBusy(true);setMessage("");try{const user=auth.currentUser;if(!user)throw new Error("Your The Plug session is no longer signed in.");const token=await getCurrentDeviceToken();if(!token)throw new Error("This device is not registered for The Plug notifications yet.");await saveNotificationToken(userUid,token,admin);const idToken=await getIdToken(user,true);const response=await fetch("/api/notifications/test",{method:"POST",headers:{Authorization:"Bearer "+idToken,"Content-Type":"application/json"},body:JSON.stringify({deviceToken:token})});const result=await response.json() as {sent?:boolean;error?:string};if(!response.ok||!result.sent)throw new Error(result.error||"The Plug could not send the test notification.");setMessage(admin?"Kitchen test sent — this device should now show a The Plug kitchen alert.":"Test sent — this device should now show a The Plug notification.");}catch(error){setMessage(error instanceof Error?error.message:"Test notification could not be sent. Check your notification setup.")}finally{setBusy(false)}}
 async function saveLead(value:number){if(!userUid)return;setBusy(true);setMessage("");try{const next={...prefs,leadMinutes:value,updatedAt:new Date().toISOString()};await saveNotificationPreferences(userUid,next);setPrefs(next);setMessage("Saved. The Plug will remind you "+value+" minutes before pickup.");}catch{setMessage("Notification timing could not be saved.")}finally{setBusy(false)}}
 if(!userUid)return null;
 return <section className="notificationSettings"><div className="panelHeading"><div><span className="kicker">Settings · Notifications</span><h2>{admin?"Kitchen notifications.":"Pickup reminders."}</h2></div><span className="orderTruth">{prefs.enabled?"Enabled on this device":"Not enabled"}</span></div><p>{admin?"Enable this device to receive new-order alerts as soon as customers submit orders, plus scheduled pickup reminders.":"Choose when The Plug should remind you before a scheduled pickup."} The default is 15 minutes. Notifications are only sent after you give this device permission.</p>{!prefs.enabled?<button className="button buttonPrimary" type="button" onClick={()=>void enable()} disabled={busy}>{busy?"Setting up…":admin?"Enable kitchen notifications":"Enable pickup notifications"}</button>:<><div className="notificationChoice"><label>Remind me before pickup<select value={prefs.leadMinutes} onChange={e=>void saveLead(Number(e.target.value))} disabled={busy}>{LEAD_OPTIONS.map(value=><option key={value} value={value}>{value} minutes before</option>)}</select></label></div><p className="orderTruth">{admin?"This kitchen device can receive new-order alerts and scheduled pickup reminders.":"This device can receive reminders for your The Plug pickup orders."} When a notification appears, tapping it opens {admin?"Kitchen Control so you can review the order or request.":"My The Plug so you can see your saved orders."} It does not change, cancel or resubmit the order.</p><button className="button buttonLight" type="button" onClick={()=>void testNotification()} disabled={busy}>{busy?"Sending test…":"Send a test notification"}</button></>}{message&&<p className="notice" role="status">{message}</p>}</section>;
}