"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {collection,onSnapshot} from "firebase/firestore";
import {db} from "@/lib/firebase/client";
import AdminConversations from "@/components/AdminConversations";
import {subscribeToAllPlugRequests,updatePlugRequest,type PlugRequest,type PlugRequestStatus,PLUG_REQUEST_STATUSES} from "@/lib/firebase/plug-data";

const WHATSAPP_CATALOG="https://wa.me/c/26776411150";
const WHATSAPP="https://wa.me/26776411150";
const money=(n:number)=>"P"+n.toFixed(2);
type JourneyEvent={id:string;uid:string;event:string;details?:{productLabel?:string;itemType?:string;source?:string;requestId?:string};createdAt:string};

export default function PlugAdminDashboard(){
 const[requests,setRequests]=useState<PlugRequest[]>([]),[tab,setTab]=useState<"requests"|"whatsapp"|"inbox">("requests"),[selected,setSelected]=useState<PlugRequest|null>(null),[draft,setDraft]=useState<PlugRequest|null>(null),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[journeyEvents,setJourneyEvents]=useState<JourneyEvent[]>([]),[analyticsNotice,setAnalyticsNotice]=useState("");
 useEffect(()=>{const stop=subscribeToAllPlugRequests(next=>{setRequests(next);setLoading(false)},error=>{setNotice(error.message);setLoading(false)});return()=>stop()},[]);
 useEffect(()=>{return onSnapshot(collection(db,"customerJourneyEvents"),snapshot=>{setJourneyEvents(snapshot.docs.map(d=>({id:d.id,...d.data()} as JourneyEvent)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setAnalyticsNotice("");},()=>setAnalyticsNotice("Journey analytics are not available yet. Confirm the Firebase rules are published for customerJourneyEvents and that server analytics credentials are configured."))},[]);
 const journeySummary=useMemo(()=>{const count=(event:string)=>journeyEvents.filter(item=>item.event===event).length;const products=new Map<string,number>();for(const item of journeyEvents){const label=item.details?.productLabel;if(label&&["storefront_find_opened","storefront_offer_opened","product_request_clicked","product_shared","request_submitted"].includes(item.event))products.set(label,(products.get(label)||0)+1)}return {visits:count("request_flow_opened"),confirmed:count("account_confirmed"),notifications:count("notification_enabled"),invites:count("friend_invite_created"),requests:count("request_submitted"),shares:count("product_shared"),catalogue:count("catalogue_opened"),instagram:count("instagram_opened"),products:[...products.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)}},[journeyEvents]);
 const active=useMemo(()=>requests.filter(r=>!["Delivered","Collected","Cancelled"].includes(r.status)),[requests]);
 async function saveRequest(){if(!draft)return;setNotice("");if(["Deposit Received","Sourcing","In Transit","Ready","Delivered","Collected"].includes(draft.status)&&!draft.customerApprovedAt){setNotice("Record customer quote approval before moving this request beyond the deposit stage.");return}try{const updatedAt=new Date().toISOString();await updatePlugRequest(draft.id,{status:draft.status,quotedPrice:draft.quotedPrice,depositRequired:draft.depositRequired,depositPaid:draft.depositPaid,deliveryEstimate:draft.deliveryEstimate,deliveryMethod:draft.deliveryMethod,deliveryDetails:draft.deliveryDetails,adminNote:draft.adminNote});const next={...draft,updatedAt};setRequests(current=>current.map(item=>item.id===draft.id?next:item));setSelected(next);setDraft(next);try{await fetch("/api/notifications/request-updated",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:draft.id})})}catch{}setNotice("Request update saved.")}catch{setNotice("Request update was not confirmed. Check Firebase access and try again.")}}
 return <main className="adminPage"><div className="adminShell">
  <header className="adminHeader"><div><span className="kicker">THE PLUG · OPERATIONS</span><h1>Frank&apos;s dashboard</h1><p>Run sourcing requests from quote through deposit, sourcing and delivery.</p></div><div className="adminHeaderActions"><Link href="/admin/storefront" className="button buttonPrimary">Storefront studio ↗</Link><Link href="/admin/community" className="button buttonLight">Community feed ↗</Link><Link href="/" className="button buttonLight">Open storefront</Link></div></header>
  <section className="journeyAnalytics"><div className="panelHeading"><div><span className="kicker">CUSTOMER JOURNEY · LIVE EVENTS</span><h2>What moves people?</h2><p className="orderTruth">Interaction events from The Plug. Counts are event totals, not unique people or conversion rates.</p></div></div><div className="journeyAnalyticsGrid"><article><span>Request flow opened</span><strong>{journeySummary.visits}</strong></article><article><span>Accounts confirmed</span><strong>{journeySummary.confirmed}</strong></article><article><span>Requests submitted</span><strong>{journeySummary.requests}</strong></article><article><span>Friend invites created</span><strong>{journeySummary.invites}</strong></article><article><span>Finds shared</span><strong>{journeySummary.shares}</strong></article><article><span>Notifications enabled</span><strong>{journeySummary.notifications}</strong></article><article><span>WhatsApp catalogue opens</span><strong>{journeySummary.catalogue}</strong></article><article><span>Instagram opens</span><strong>{journeySummary.instagram}</strong></article></div>{journeySummary.products.length>0&&<div className="journeyAnalyticsProducts"><strong>Finds attracting activity</strong>{journeySummary.products.map(([label,count])=><div key={label}><span>{label}</span><b>{count}</b></div>)}</div>}{analyticsNotice&&<p className="notice" role="status">{analyticsNotice}</p>}</section>
  <nav className="adminTabs"><button className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}>Requests {active.length>0?"("+active.length+")":""}</button><button className={tab==="whatsapp"?"active":""} onClick={()=>setTab("whatsapp")}>WhatsApp catalogue</button><button className={tab==="inbox"?"active":""} onClick={()=>setTab("inbox")}>Customer inbox</button></nav>
  {notice&&<p className="notice" role="status">{notice}</p>}
  {tab==="requests"&&<section className="adminPanel"><div className="panelHeading"><div><span className="kicker">Sourcing queue</span><h2>Customer requests</h2><p className="orderTruth">New request → quote → 50% deposit → sourcing → in transit → ready → delivered/collected.</p></div></div>{loading?<div className="emptyState">Loading sourcing queue…</div>:requests.length===0?<div className="emptyState">No sourcing requests yet.</div>:<div className="queue">{requests.map(request=><article className="queueRow" key={request.id}><div><strong>{request.product}</strong><small>{request.customerName} · {request.phone}</small><small>{request.size||"Size not specified"} · {request.colour||"Colour not specified"}</small><small>{request.quotedPrice!==undefined?money(request.quotedPrice):"Quote not set"} · {request.depositPaid!==undefined?money(request.depositPaid)+" paid":"Deposit not recorded"}</small></div><div className="queueActions"><strong>{request.status}</strong><button className="button buttonLight" onClick={()=>{setSelected(request);setDraft({...request})}}>Manage</button></div></article>)}</div>}</section>}
  {selected&&draft&&<section className="adminPanel"><div className="panelHeading"><div><span className="kicker">Request {selected.id.slice(0,8).toUpperCase()}</span><h2>{selected.product}</h2><p>{selected.customerName} · {selected.phone}</p></div><button className="button buttonLight" onClick={()=>{setSelected(null);setDraft(null)}}>Close</button></div><div className="adminTwoCol"><div className="adminForm"><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as PlugRequestStatus})}>{PLUG_REQUEST_STATUSES.map(status=><option key={status}>{status}</option>)}</select></label><label>Current quote (P)<input type="number" min="0" step="0.01" value={draft.quotedPrice??""} onChange={e=>setDraft({...draft,quotedPrice:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>50% deposit required (P)<input type="number" min="0" step="0.01" value={draft.depositRequired??(draft.quotedPrice!==undefined?draft.quotedPrice/2:"")} onChange={e=>setDraft({...draft,depositRequired:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>Deposit actually received (P)<input type="number" min="0" step="0.01" value={draft.depositPaid??""} onChange={e=>setDraft({...draft,depositPaid:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>Delivery / sourcing expectation<input value={draft.deliveryEstimate??""} onChange={e=>setDraft({...draft,deliveryEstimate:e.target.value})} placeholder="e.g. 3–4 weeks from deposit"/></label><label>Fulfilment method<select value={draft.deliveryMethod??"delivery"} onChange={e=>setDraft({...draft,deliveryMethod:e.target.value as "delivery"|"collection"})}><option value="delivery">Delivery</option><option value="collection">Collection</option></select></label><label>Delivery / collection details<textarea value={draft.deliveryDetails??""} onChange={e=>setDraft({...draft,deliveryDetails:e.target.value})}/></label><label>Message to customer<textarea value={draft.adminNote??""} onChange={e=>setDraft({...draft,adminNote:e.target.value})} placeholder="What should the customer know right now?"/></label><div className="saveAction"><button className="button buttonPrimary" onClick={()=>void saveRequest()}>Save request update</button></div></div><div className="requestBand"><strong>Customer request</strong><p>{draft.product}</p><p>Size: {draft.size||"Not specified"} · Colour: {draft.colour||"Not specified"}</p>{draft.notes&&<p>Notes: {draft.notes}</p>}{draft.attachment&&<a href={draft.attachment.url} target="_blank" rel="noreferrer">Open customer attachment</a>}<p className="orderTruth">Customer quote approval: {draft.customerApprovedAt?"recorded":"not recorded"}.</p><p className="orderTruth">Do not mark Deposit Received until Frank has actually recorded the agreed deposit.</p></div></div></section>}
  {tab==="whatsapp"&&<section className="adminPanel"><div className="panelHeading"><div><span className="kicker">Source of truth</span><h2>WhatsApp catalogue</h2><p>Products stay managed in the WhatsApp Business app. The Plug deliberately does not create a second product-entry system.</p></div></div><div className="adminTwoCol"><div className="requestBand"><strong>Live catalogue</strong><p>The customer-facing catalogue is the existing WhatsApp catalogue. Keep adding, editing and hiding products there exactly as you do today.</p><a className="button buttonPrimary" href={WHATSAPP_CATALOG} target="_blank" rel="noreferrer">Open WhatsApp catalogue</a></div><div className="requestBand"><strong>Customer ordering</strong><p>When a customer chooses a listed product, they continue into WhatsApp to ask questions and place the order. The Plug remains responsible for sourcing requests and order tracking.</p><a className="button buttonLight" href={WHATSAPP} target="_blank" rel="noreferrer">Open WhatsApp chat</a></div></div><p className="orderTruth">No duplicate catalogue. No re-entering products. No second inventory workflow.</p></section>}
  {tab==="inbox"&&<section className="adminPanel"><AdminConversations/></section>}
 </div></main>;
}