"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {getDownloadURL,ref,uploadBytes} from "firebase/storage";
import AdminConversations from "@/components/AdminConversations";
import {storage} from "@/lib/firebase/client";
import {deleteMenuItem,getMenuItems,saveMenuItem,type MenuItem} from "@/lib/firebase/data";
import {PLUG_REQUEST_STATUSES,subscribeToAllPlugRequests,updatePlugRequest,type PlugRequest,type PlugRequestStatus} from "@/lib/firebase/plug-data";

const money=(n:number)=>"P"+n.toFixed(2);
const blank:MenuItem={id:"",name:"",price:0,category:"Sneakers",description:"",available:true,preparationMinutes:0,sortOrder:0,section:"deal",days:[]};

export default function PlugAdminDashboard(){
 const[requests,setRequests]=useState<PlugRequest[]>([]),[menu,setMenu]=useState<MenuItem[]>([]),[tab,setTab]=useState<"requests"|"catalogue"|"inbox">("requests"),[selected,setSelected]=useState<PlugRequest|null>(null),[draft,setDraft]=useState<PlugRequest|null>(null),[menuDraft,setMenuDraft]=useState<MenuItem>(blank),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false);
 useEffect(()=>{const stop=subscribeToAllPlugRequests(next=>{setRequests(next);setLoading(false)},error=>{setNotice(error.message);setLoading(false)});void getMenuItems().then(setMenu).catch(()=>setNotice("Catalogue could not be loaded. The Plug is still being connected to its dedicated Firebase project."));return()=>stop()},[]);
 const active=useMemo(()=>requests.filter(r=>!["Delivered","Collected","Cancelled"].includes(r.status)),[requests]);
 async function saveRequest(){if(!draft)return;setNotice("");try{const updatedAt=new Date().toISOString();await updatePlugRequest(draft.id,{status:draft.status,quotedPrice:draft.quotedPrice,depositRequired:draft.depositRequired,depositPaid:draft.depositPaid,deliveryEstimate:draft.deliveryEstimate,deliveryMethod:draft.deliveryMethod,deliveryDetails:draft.deliveryDetails,adminNote:draft.adminNote});const next={...draft,updatedAt};setRequests(current=>current.map(item=>item.id===draft.id?next:item));setSelected(next);setDraft(next);try{await fetch("/api/notifications/request-updated",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:draft.id})})}catch{}setNotice("Request update saved.")}catch{setNotice("Request update was not confirmed. Check Firebase access and try again.")}}
 async function saveCatalogue(){if(!menuDraft.name.trim()){setNotice("Add a product name.");return}try{const clean={...menuDraft,id:menuDraft.id||crypto.randomUUID(),name:menuDraft.name.trim(),category:menuDraft.category.trim()||"Other",description:menuDraft.description.trim(),price:Number(menuDraft.price)||0,available:menuDraft.available,preparationMinutes:0,sortOrder:Number(menuDraft.sortOrder)||0,section:"deal" as const,days:[],...(menuDraft.brand?.trim()?{brand:menuDraft.brand.trim()}:{}),...(menuDraft.productType?.trim()?{productType:menuDraft.productType.trim()}:{}),...(menuDraft.sizes?.length?{sizes:menuDraft.sizes}:{}),...(menuDraft.colors?.length?{colors:menuDraft.colors}:{}),...(menuDraft.sourceUrl?.trim()?{sourceUrl:menuDraft.sourceUrl.trim()}:{}),...(menuDraft.imageUrl?{imageUrl:menuDraft.imageUrl}:{})};await saveMenuItem(clean);setMenu(current=>[...current.filter(x=>x.id!==clean.id),clean].sort((a,b)=>a.sortOrder-b.sortOrder));setMenuDraft({...blank,sortOrder:menu.length+1});setNotice("Catalogue product published.")}catch{setNotice("Catalogue product could not be saved.")}}
 async function uploadPhoto(file:File){setUploading(true);try{const uploaded=await uploadBytes(ref(storage,"catalogue/"+crypto.randomUUID()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"-")),file,{contentType:file.type});const url=await getDownloadURL(uploaded.ref);setMenuDraft(current=>({...current,imageUrl:url}))}catch{setNotice("Product image could not be uploaded.")}finally{setUploading(false)}}
 return <main className="adminPage"><div className="adminShell">
  <header className="adminHeader"><div><span className="kicker">THE PLUG · OPERATIONS</span><h1>Frank&apos;s dashboard</h1><p>Run sourcing requests from quote through deposit, sourcing and delivery.</p></div><Link href="/" className="button buttonLight">Open storefront</Link></header>
  <nav className="adminTabs"><button className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}>Requests {active.length>0?"("+active.length+")":""}</button><button className={tab==="catalogue"?"active":""} onClick={()=>setTab("catalogue")}>Catalogue</button><button className={tab==="inbox"?"active":""} onClick={()=>setTab("inbox")}>Customer inbox</button></nav>
  {notice&&<p className="notice" role="status">{notice}</p>}
  {tab==="requests"&&<section className="adminPanel"><div className="panelHeading"><div><span className="kicker">Sourcing queue</span><h2>Customer requests</h2><p className="orderTruth">New request → quote → 50% deposit → sourcing → in transit → ready → delivered/collected.</p></div></div>{loading?<div className="emptyState">Loading sourcing queue…</div>:requests.length===0?<div className="emptyState">No sourcing requests yet.</div>:<div className="queue">{requests.map(request=><article className="queueRow" key={request.id}><div><strong>{request.product}</strong><small>{request.customerName} · {request.phone}</small><small>{request.size||"Size not specified"} · {request.colour||"Colour not specified"}</small><small>{request.quotedPrice!==undefined?money(request.quotedPrice):"Quote not set"} · {request.depositPaid!==undefined?money(request.depositPaid)+" paid":"Deposit not recorded"}</small></div><div className="queueActions"><strong>{request.status}</strong><button className="button buttonLight" onClick={()=>{setSelected(request);setDraft({...request})}}>Manage</button></div></article>)}</div>}</section>}
  {selected&&draft&&<section className="adminPanel"><div className="panelHeading"><div><span className="kicker">Request {selected.id.slice(0,8).toUpperCase()}</span><h2>{selected.product}</h2><p>{selected.customerName} · {selected.phone}</p></div><button className="button buttonLight" onClick={()=>{setSelected(null);setDraft(null)}}>Close</button></div><div className="adminTwoCol"><div className="adminForm"><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as PlugRequestStatus})}>{PLUG_REQUEST_STATUSES.map(status=><option key={status}>{status}</option>)}</select></label><label>Current quote (P)<input type="number" min="0" step="0.01" value={draft.quotedPrice??""} onChange={e=>setDraft({...draft,quotedPrice:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>50% deposit required (P)<input type="number" min="0" step="0.01" value={draft.depositRequired??(draft.quotedPrice!==undefined?draft.quotedPrice/2:"")} onChange={e=>setDraft({...draft,depositRequired:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>Deposit actually received (P)<input type="number" min="0" step="0.01" value={draft.depositPaid??""} onChange={e=>setDraft({...draft,depositPaid:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>Delivery / sourcing expectation<input value={draft.deliveryEstimate??""} onChange={e=>setDraft({...draft,deliveryEstimate:e.target.value})} placeholder="e.g. 3–4 weeks from deposit"/></label><label>Fulfilment method<select value={draft.deliveryMethod??"delivery"} onChange={e=>setDraft({...draft,deliveryMethod:e.target.value as "delivery"|"collection"})}><option value="delivery">Delivery</option><option value="collection">Collection</option></select></label><label>Delivery / collection details<textarea value={draft.deliveryDetails??""} onChange={e=>setDraft({...draft,deliveryDetails:e.target.value})}/></label><label>Message to customer<textarea value={draft.adminNote??""} onChange={e=>setDraft({...draft,adminNote:e.target.value})} placeholder="What should the customer know right now?"/></label><div className="saveAction"><button className="button buttonPrimary" onClick={()=>void saveRequest()}>Save request update</button></div></div><div className="requestBand"><strong>Customer request</strong><p>{draft.product}</p><p>Size: {draft.size||"Not specified"} · Colour: {draft.colour||"Not specified"}</p>{draft.notes&&<p>Notes: {draft.notes}</p>}{draft.attachment&&<a href={draft.attachment.url} target="_blank" rel="noreferrer">Open customer image</a>}<p className="orderTruth">Do not mark Deposit Received until Frank has actually recorded the agreed deposit.</p></div></div></section>}
  {tab==="catalogue"&&<section className="adminPanel"><div className="panelHeading"><div><span className="kicker">Storefront</span><h2>Catalogue</h2></div></div><div className="adminTwoCol"><form className="adminForm" onSubmit={e=>{e.preventDefault();void saveCatalogue()}}><label>Product name<input value={menuDraft.name} onChange={e=>setMenuDraft({...menuDraft,name:e.target.value})} required/></label><label>Price (P)<input type="number" min="0" step="0.01" value={menuDraft.price} onChange={e=>setMenuDraft({...menuDraft,price:Number(e.target.value)})}/></label><label>Brand<input value={menuDraft.brand??""} onChange={e=>setMenuDraft({...menuDraft,brand:e.target.value})}/></label><label>Product type<input value={menuDraft.productType??""} onChange={e=>setMenuDraft({...menuDraft,productType:e.target.value})}/></label><label>Sizes<input value={(menuDraft.sizes??[]).join(", ")} onChange={e=>setMenuDraft({...menuDraft,sizes:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label>Colours<input value={(menuDraft.colors??[]).join(", ")} onChange={e=>setMenuDraft({...menuDraft,colors:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label>Source / reference link<input type="url" value={menuDraft.sourceUrl??""} onChange={e=>setMenuDraft({...menuDraft,sourceUrl:e.target.value})}/></label><label>Category<input value={menuDraft.category} onChange={e=>setMenuDraft({...menuDraft,category:e.target.value})}/></label><label>Description<textarea value={menuDraft.description} onChange={e=>setMenuDraft({...menuDraft,description:e.target.value})}/></label><label>Product image<input type="file" accept="image/*" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadPhoto(file)}}/>{menuDraft.imageUrl&&<small>Image attached ✓</small>}</label><label className="checkRow"><input type="checkbox" checked={menuDraft.available} onChange={e=>setMenuDraft({...menuDraft,available:e.target.checked})}/> Published to customers</label><button className="button buttonPrimary" type="submit">Save catalogue product</button></form><div className="menuAdminList">{menu.map(item=><article key={item.id}><div>{item.imageUrl&&<img className="menuThumb" src={item.imageUrl} alt=""/>}<strong>{item.name}</strong><small>{item.brand||item.category} · {money(item.price)} · {item.available?"Published":"Hidden"}</small></div><div><button className="button buttonLight" onClick={()=>setMenuDraft(item)}>Edit</button><button className="button buttonDanger" onClick={()=>void deleteMenuItem(item.id).then(()=>setMenu(current=>current.filter(x=>x.id!==item.id))).catch(()=>setNotice("Product could not be deleted."))}>Delete</button></div></article>)}</div></div></section>}
  {tab==="inbox"&&<section className="adminPanel"><AdminConversations/></section>}
 </div></main>;
}
