"use client";
import Link from "next/link";
import {collection,onSnapshot,query,where} from "firebase/firestore";
import {useEffect,useMemo,useRef,useState} from "react";
import {db} from "@/lib/firebase/client";
import {trackPlugJourney} from "@/lib/firebase/journey-analytics";
type StorefrontItem={id:string;type:"find"|"deal";title:string;description:string;imageUrl:string;price?:number;status:string;audience:string;startsAt?:string;endsAt?:string;ctaLabel?:string;sortOrder?:number;updatedAt?:string};
function isLive(item:StorefrontItem,now:number){return (item.status==="published"||item.status==="scheduled")&&item.audience==="everyone"&&(!item.startsAt||new Date(item.startsAt).getTime()<=now)&&(!item.endsAt||new Date(item.endsAt).getTime()>=now);}
function money(value:number){return new Intl.NumberFormat("en-BW",{style:"currency",currency:"BWP",maximumFractionDigits:2}).format(value);}
function ProductCard({item}:{item:StorefrontItem}){const url="/request?product="+encodeURIComponent(item.title);const[expanded,setExpanded]=useState(false);function toggleDetails(){const next=!expanded;setExpanded(next);if(next)void trackPlugJourney(item.type==="deal"?"storefront_offer_opened":"storefront_find_opened",{productLabel:item.title,itemType:item.type,source:"storefront"});}async function shareItem(){void trackPlugJourney("product_share_clicked",{productLabel:item.title,itemType:item.type,source:"storefront"});const url=window.location.origin+"/request?product="+encodeURIComponent(item.title);try{if(navigator.share){await navigator.share({title:item.title,text:"A find from The Plug you might like.",url});void trackPlugJourney("product_shared",{productLabel:item.title,itemType:item.type,source:"native_share"});}else{await navigator.clipboard.writeText(url);void trackPlugJourney("product_shared",{productLabel:item.title,itemType:item.type,source:"copied_link"});}}catch(error){if(!(error instanceof Error&&error.name==="AbortError"))console.warn("The Plug share link could not be opened",error)}}return <article className="plugProductCard"><button type="button" onClick={toggleDetails} className="plugProductImageLink" aria-expanded={expanded} aria-label={(expanded?"Hide details for ":"View details for ")+item.title}><div className={"plugProductImage "+(item.imageUrl?"":"plugProductImageMissing")}>{item.imageUrl?<img src={item.imageUrl} alt="" loading="lazy"/>:<span>THE<br/>PLUG</span>}{item.type==="deal"&&<span className="plugProductBadge">LIVE OFFER</span>}</div></button><div className="plugProductMeta"><span>{item.type==="deal"?"THE OFFER EDIT":"FRANK’S PICKS"}</span>{typeof item.price==="number"&&<strong>{money(item.price)}</strong>}</div><h3>{item.title}</h3>{item.description&&<p>{item.description}</p>}<button type="button" className="plugProductAction" aria-expanded={expanded} onClick={toggleDetails}>{expanded?"Hide details":"View details"} <span>{expanded?"−":"↗"}</span></button>{expanded&&<div className="plugProductExpanded"><p>Want this exact find? Add your size or colour in a private request. Frank still confirms current price and availability.</p><div className="plugProductExpandedActions"><Link className="plugProductExpandedAction" href={url} onClick={()=>void trackPlugJourney("product_request_clicked",{productLabel:item.title,itemType:item.type,source:"storefront"})}>{item.ctaLabel||(item.type==="deal"?"Ask about this offer":"Request this find")} ↗</Link><button type="button" className="plugProductShareAction" onClick={()=>void shareItem()}>Know someone who’d want this? Share ↗</button></div></div>}</article>}
export default function StorefrontFeed(){const[items,setItems]=useState<StorefrontItem[]>([]),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false),[now,setNow]=useState(()=>Date.now());const findRail=useRef<HTMLDivElement>(null),dealRail=useRef<HTMLDivElement>(null);
useEffect(()=>{let settled=false;const timeout=window.setTimeout(()=>{if(!settled){setLoaded(true);setFailed(true);}},1500);const q=query(collection(db,"storefrontContent"),where("status","in",["published","scheduled"]),where("audience","==","everyone"));const stop=onSnapshot(q,s=>{settled=true;window.clearTimeout(timeout);setItems(s.docs.map(d=>({id:d.id,...d.data()} as StorefrontItem)));setLoaded(true);setFailed(false);},()=>{settled=true;window.clearTimeout(timeout);setItems([]);setLoaded(true);setFailed(true);});return()=>{window.clearTimeout(timeout);stop();};},[]);
useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(id);},[]);
const live=useMemo(()=>items.filter(item=>isLive(item,now)).sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999)),[items,now]);const finds=live.filter(i=>i.type==="find"),deals=live.filter(i=>i.type==="deal");
function move(rail:React.RefObject<HTMLDivElement|null>,direction:number){rail.current?.scrollBy({left:direction*Math.max(280,rail.current.clientWidth*.75),behavior:"smooth"});}
return <><section className="plugStoreSection" id="featured"><div className="plugContainer"><div className="plugStoreSectionHead"><div><span className="plugKicker">01 / THE CURRENT EDIT</span><h2>Featured <em>finds.</em></h2><p>Frank’s latest picks.</p></div><div className="plugRailControls"><button aria-label="Previous featured finds" onClick={()=>move(findRail,-1)}>←</button><button aria-label="Next featured finds" onClick={()=>move(findRail,1)}>→</button></div></div>
{!loaded?<div className="plugContentLoading">Opening the edit…</div>:finds.length?<div className="plugProductRail" ref={findRail}>{finds.map(item=><ProductCard item={item} key={item.id}/>)}</div>:<div className="plugEmptyEdit"><div className="plugEmptyIndex">THE PLUG<br/>001</div><div><span>{failed?"THE EDIT IS RESTING":"FRANK’S PICKS"}</span><h3>{failed?"We couldn’t load the latest finds.":"The next find starts here."}</h3><p>{failed?"Try again in a moment. The edit will be here when it loads.":"Frank’s featured items will appear here as soon as he publishes them."}</p><Link href="/request">Looking for something specific? Request it ↗</Link></div><div className="plugEmptySpark">✳</div></div>}</div></section>
<section className="plugStoreSection plugDealsSection" id="deals"><div className="plugContainer"><div className="plugStoreSectionHead"><div><span className="plugKicker">02 / LIMITED EDITIONS</span><h2>Live <em>offers.</em></h2><p>Only offers Frank has published and marked active.</p></div><div className="plugRailControls"><button aria-label="Previous live offers" onClick={()=>move(dealRail,-1)}>←</button><button aria-label="Next live offers" onClick={()=>move(dealRail,1)}>→</button></div></div>
{!loaded?<div className="plugContentLoading">Checking live offers…</div>:deals.length?<div className="plugProductRail" ref={dealRail}>{deals.map(item=><ProductCard item={item} key={item.id}/>)}</div>:<div className="plugDealEmptyEditorial"><div className="plugDealSymbol">%</div><div><span>NO ACTIVE OFFERS</span><h3>{failed?"Offers are taking a moment to load.":"Good timing is coming."}</h3><p>{failed?"Check back shortly; no offer is shown until it can be verified.":"When Frank publishes a live offer, it will appear here. No invented discounts or countdowns."}</p></div><Link href="/request">Find what you want <span>↗</span></Link></div>}</div></section></>;}
