"use client";
import {addDoc,collection,deleteDoc,doc,onSnapshot,updateDoc} from "firebase/firestore";
import {getDownloadURL,ref,uploadBytes} from "firebase/storage";
import {useEffect,useState} from "react";
import {db,storage} from "@/lib/firebase/client";
type Kind="find"|"deal";type Status="draft"|"scheduled"|"published"|"paused"|"archived";type Audience="everyone"|"circle";
type Item={id:string;type:Kind;title:string;description:string;imageUrl:string;price?:number;status:Status;audience:Audience;startsAt:string;endsAt:string;ctaLabel:string;sortOrder:number;createdAt:string;updatedAt:string};
type Draft=Omit<Item,"id">&{id?:string;priceText:string};
const blank=():Draft=>({type:"find",title:"",description:"",imageUrl:"",status:"draft",audience:"everyone",startsAt:"",endsAt:"",ctaLabel:"",sortOrder:0,createdAt:"",updatedAt:"",priceText:""});
const statuses:Status[]=["draft","scheduled","published","paused","archived"];
export default function StorefrontPublishing(){const[items,setItems]=useState<Item[]>([]),[draft,setDraft]=useState<Draft>(blank()),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[notice,setNotice]=useState("");
useEffect(()=>onSnapshot(collection(db,"storefrontContent"),s=>{setItems(s.docs.map(d=>({id:d.id,...d.data()} as Item)).sort((a,b)=>(b.updatedAt||"").localeCompare(a.updatedAt||"")));setLoading(false);},()=>{setNotice("Could not load storefront content. Check admin access and Firebase rules.");setLoading(false);}),[]);
function fresh(){setDraft(blank());setNotice("");}function edit(item:Item){setDraft({...item,priceText:typeof item.price==="number"?String(item.price):""});setNotice("");window.scrollTo({top:0,behavior:"smooth"});}
async function uploadImage(file?:File){if(!file)return;if(!file.type.startsWith("image/")){setNotice("Choose an image file.");return;}if(file.size>12*1024*1024){setNotice("Choose an image under 12 MB.");return;}setUploading(true);setNotice("");try{const name=file.name.replace(/[^a-zA-Z0-9._-]/g,"-").slice(-90);const imageRef=ref(storage,"storefrontMedia/"+Date.now()+"-"+name);const uploaded=await uploadBytes(imageRef,file,{contentType:file.type});const url=await getDownloadURL(uploaded.ref);setDraft(d=>({...d,imageUrl:url}));}catch{setNotice("Image upload was not confirmed. Check Firebase Storage access and try again.");}finally{setUploading(false);}}
async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setNotice("");if(!draft.title.trim()){setNotice("Add a title first.");setSaving(false);return;}if(draft.priceText.trim()&&(!Number.isFinite(Number(draft.priceText))||Number(draft.priceText)<0)){setNotice("Enter a valid price in pula.");setSaving(false);return;}const now=new Date().toISOString();const payload:Record<string,unknown>={type:draft.type,title:draft.title.trim(),description:draft.description.trim(),imageUrl:draft.imageUrl.trim(),status:draft.status,audience:draft.audience,startsAt:draft.startsAt,endsAt:draft.endsAt,ctaLabel:draft.ctaLabel.trim(),sortOrder:Number(draft.sortOrder)||0,createdAt:draft.createdAt||now,updatedAt:now};if(draft.priceText.trim())payload.price=Number(draft.priceText);
try{if(draft.id)await updateDoc(doc(db,"storefrontContent",draft.id),payload);else await addDoc(collection(db,"storefrontContent"),payload);setNotice(draft.status==="published"?"Saved. Published content appears when its audience and active dates allow it.":"Saved as "+draft.status+". It is not shown in the public storefront.");fresh();}catch{setNotice("Save was not confirmed. Check admin access and Firebase rules before trying again.");}finally{setSaving(false);}}
async function setStatus(item:Item,status:Status){setNotice("");try{await updateDoc(doc(db,"storefrontContent",item.id),{status,updatedAt:new Date().toISOString()});setNotice(item.title+": "+status+".");}catch{setNotice("That change was not confirmed. Check admin access and try again.");}}
async function remove(item:Item){if(!window.confirm("Permanently delete “"+item.title+"”? Use Archive if you may need it again."))return;try{await deleteDoc(doc(db,"storefrontContent",item.id));setNotice("Content deleted.");if(draft.id===item.id)fresh();}catch{setNotice("Delete was not confirmed. Check admin access and try again.");}}
return <main className="adminPage"><div className="adminShell"><header className="adminHeader"><div><span className="kicker">THE PLUG · THE EDIT</span><h1>Storefront studio</h1><p>Create and publish featured finds and live offers. Only published, in-date public content appears on the storefront.</p></div><a href="/" className="button buttonLight">View storefront ↗</a></header>
{notice&&<p className="notice" role="status">{notice}</p>}<section className="adminPanel plugStudioPanel"><div className="panelHeading"><div><span className="kicker">{draft.id?"EDIT CONTENT":"NEW CONTENT"}</span><h2>{draft.id?draft.title||"Edit item":"Create a find or offer"}</h2></div><button type="button" className="button buttonLight" onClick={fresh}>New</button></div>
<form className="adminForm plugStudioForm" onSubmit={save}><label>Content type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as Kind})}><option value="find">Featured find</option><option value="deal">Live offer</option></select></label><label>Title<input required maxLength={100} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="e.g. Nike Air Max 90"/></label><label>Price in pula (optional)<input type="number" min="0" step="0.01" value={draft.priceText} onChange={e=>setDraft({...draft,priceText:e.target.value})} placeholder="Only enter a confirmed price"/></label><label>Short description<textarea maxLength={500} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Details Frank has confirmed"/></label><label>Call to action (optional)<input maxLength={48} value={draft.ctaLabel} onChange={e=>setDraft({...draft,ctaLabel:e.target.value})} placeholder="Ask about this find"/></label><label>Audience<select value={draft.audience} onChange={e=>setDraft({...draft,audience:e.target.value as Audience})}><option value="everyone">Everyone</option><option value="circle">Confirmed Plug Circle members</option></select></label><label>Publication<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Status})}>{statuses.map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></label><label>Starts (optional)<input type="datetime-local" value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>Expires (optional)<input type="datetime-local" value={draft.endsAt} onChange={e=>setDraft({...draft,endsAt:e.target.value})}/></label><label>Display order (lower first)<input type="number" min="0" step="1" value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:Number(e.target.value)})}/></label>
<div className="plugStudioUpload"><div className="plugStudioPreview">{draft.imageUrl?<img src={draft.imageUrl} alt="Content preview"/>:<span>IMAGE<br/>PREVIEW</span>}</div><div><strong>Campaign / product image</strong><p>Upload a real product or campaign image (max 12 MB).</p><label className="button buttonLight plugUploadButton">{uploading?"Uploading…":"Choose image"}<input type="file" accept="image/*" disabled={uploading} onChange={e=>void uploadImage(e.target.files?.[0])}/></label>{draft.imageUrl&&<button type="button" className="plugRemoveImage" onClick={()=>setDraft({...draft,imageUrl:""})}>Remove image</button>}</div></div>
<button className="button buttonPrimary" type="submit" disabled={saving||uploading}>{saving?"Saving…":draft.id?"Save changes":"Create content"}</button></form></section>
<section className="adminPanel"><div className="panelHeading"><div><span className="kicker">PUBLISHING QUEUE</span><h2>Everything in the edit</h2><p>Draft, publish, pause, archive or delete content.</p></div></div>{loading?<div className="emptyState">Loading content…</div>:items.length===0?<div className="emptyState">Nothing created yet. Add the first find or offer above.</div>:<div className="plugStudioList">{items.map(item=><article className="plugStudioRow" key={item.id}><div className="plugStudioThumb">{item.imageUrl?<img src={item.imageUrl} alt=""/>:<span>THE<br/>PLUG</span>}</div><div className="plugStudioRowInfo"><div className="plugStudioRowMeta"><span>{item.type==="deal"?"LIVE OFFER":"FEATURED FIND"}</span><b className={"plugStatus plugStatus-"+item.status}>{item.status}</b></div><strong>{item.title}</strong><small>{item.audience==="circle"?"Confirmed members":"Everyone"}{typeof item.price==="number"?" · P"+item.price.toFixed(2):""}{item.endsAt?" · Ends "+item.endsAt.replace("T"," "):""}</small></div><div className="plugStudioRowActions"><button className="button buttonLight" onClick={()=>edit(item)}>Edit</button>{item.status!=="published"&&<button className="button buttonPrimary" onClick={()=>void setStatus(item,"published")}>Publish</button>}{item.status==="published"&&<button className="button buttonLight" onClick={()=>void setStatus(item,"paused")}>Pause</button>}{item.status!=="archived"&&<button className="plugArchiveButton" onClick={()=>void setStatus(item,"archived")}>Archive</button>}<button className="plugArchiveButton" onClick={()=>void remove(item)}>Delete</button></div></article>)}</div>}</section></div></main>;}
