"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getMenuItems,readCachedMenuItems,type MenuItem} from "@/lib/firebase/data";
const money=(n:number)=>`P${n.toFixed(n%1?2:0)}`;
export default function ProductDetail(){
 const[id,setId]=useState(""),[item,setItem]=useState<MenuItem|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{const value=window.location.pathname.split("/").pop()||"";setId(value);void getMenuItems().then(items=>setItem(items.find(x=>x.id===value)||null)).catch(()=>setItem(readCachedMenuItems().find(x=>x.id===value)||null)).finally(()=>setLoading(false))},[]);
 if(loading)return <main className="plugDetailPage"><div className="plugContainer plugDetailEmpty">Loading product…</div></main>;
 if(!item)return <main className="plugDetailPage"><div className="plugContainer plugDetailEmpty"><strong>Product not found.</strong><p>The listing may have changed or may be temporarily unavailable.</p><Link href="/" className="plugButton plugButtonPrimary">Back to catalogue</Link></div></main>;
 return <main className="plugDetailPage"><div className="plugContainer"><div className="plugDetailBack"><Link href="/">← Catalogue</Link></div><section className="plugDetailGrid"><div className="plugDetailMedia">{item.imageUrl?<Image src={item.imageUrl} alt={item.name} fill priority sizes="(max-width: 800px) 100vw, 55vw"/>:<div className="plugDetailPlaceholder"><span>THE PLUG</span><strong>{item.category}</strong></div>}</div><div className="plugDetailCopy"><span className="plugKicker">{item.brand||item.category}</span><h1>{item.name}</h1>{item.productType&&<p className="plugDetailType">{item.productType}</p>}<strong className="plugDetailPrice">{money(item.price)}</strong>{item.description&&<p>{item.description}</p>}{item.sizes?.length?<div className="plugChoice"><strong>Available sizes</strong><div>{item.sizes.map(size=><span key={size}>{size}</span>)}</div><small>Select the size you want when you send the request.</small></div>:null}{item.colors?.length?<div className="plugChoice"><strong>Available colours</strong><div>{item.colors.map(color=><span key={color}>{color}</span>)}</div></div>:null}<div className="plugDetailActions"><Link href={"/request?product="+encodeURIComponent(item.name)} className="plugButton plugButtonPrimary">Request this product</Link>{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer" className="plugButton plugButtonGhost">Open reference</a>}</div><div className="plugDetailTruth"><strong>Important</strong><p>The catalogue price is guidance until Frank confirms the current sourcing quote, availability and delivery expectation. A 50% deposit is due only after an order is accepted.</p></div></div></section></div></main>
}