"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {onAuthStateChanged,type User} from "firebase/auth";
import {addDoc,collection} from "firebase/firestore";
import {getDownloadURL,ref as storageRef,uploadBytes} from "firebase/storage";
import {auth,db,storage} from "@/lib/firebase/client";
import {createCustomerConversation,getCustomerProfile,recordConversationMessage,saveCustomerProfile} from "@/lib/firebase/data";
import {createPlugRequest} from "@/lib/firebase/plug-data";
export default function RequestForm(){
 const[product,setProduct]=useState(""),[user,setUser]=useState<User|null>(null),[name,setName]=useState(""),[phone,setPhone]=useState(""),[size,setSize]=useState(""),[color,setColor]=useState(""),[notes,setNotes]=useState(""),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[done,setDone]=useState(false),[nextPath,setNextPath]=useState("/request"),[authReady,setAuthReady]=useState(false);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setProduct(params.get("product")||"");setNextPath(window.location.pathname+window.location.search);return onAuthStateChanged(auth,async next=>{setUser(next);if(next&&!next.isAnonymous){const profile=await getCustomerProfile(next.uid).catch(()=>null);if(profile){setName(profile.name);setPhone(profile.phone)}}setAuthReady(true)})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;if(!user||user.isAnonymous){setMessage("Join The Plug with Google before sending a request. Your member account keeps your request and private conversation together.");return}if(!name.trim()||!phone.trim()||!product.trim()){setMessage("Add your name, WhatsApp/phone and the product you want.");return}setBusy(true);setMessage("");try{const customer=user;const now=new Date().toISOString();const conversationId=await createCustomerConversation(customer.uid,"Product sourcing request");const messageId=crypto.randomUUID();let attachment=null;if(file){if(!file.type.startsWith("image/"))throw new Error("Please choose an image file.");if(file.size>10*1024*1024)throw new Error("Images must be 10 MB or smaller.");const uploaded=await uploadBytes(storageRef(storage,`conversationAttachments/${conversationId}/${messageId}/${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`),file,{contentType:file.type});attachment={url:await getDownloadURL(uploaded.ref),name:file.name,type:file.type,size:file.size}}const text=["Product: "+product.trim(),size&&"Size: "+size.trim(),color&&"Colour: "+color.trim(),notes&&"Notes: "+notes.trim()].filter(Boolean).join("\n");
   const requestId=await createPlugRequest({customerId:customer.uid,customerName:name.trim(),phone:phone.trim(),product:product.trim(),size:size.trim(),colour:color.trim(),notes:notes.trim(),attachment,createdAt:now,updatedAt:now,status:"New Request",deliveryMethod:"delivery"});await addDoc(collection(db,"conversations",conversationId,"messages"),{senderId:customer.uid,senderRole:"customer",text,attachment,createdAt:now});await recordConversationMessage(conversationId,"customer",text||("Attachment: "+(attachment?.name||"image")));try{const response=await fetch("/api/notifications/sourcing-request",{method:"POST",headers:{Authorization:"Bearer "+(await customer.getIdToken()),"Content-Type":"application/json"},body:JSON.stringify({conversationId,messageId})});if(!response.ok)setMessage("Request saved. The instant alert could not be sent, but Frank can still see it in the sourcing queue.")}catch{setMessage("Request saved. The instant alert is unavailable while the app is being built, but Frank can still see the request when connected.")}await saveCustomerProfile({uid:customer.uid,name:name.trim(),email:customer.email??"",phone:phone.trim(),preferredDeliveryLocation:"",notes:"",createdAt:now,updatedAt:now}).catch(()=>{});setDone(true);void requestId}catch(error){setMessage(error instanceof Error?error.message:"The Plug is still being built and this request could not be saved yet. Please use WhatsApp to reach Frank directly.")}finally{setBusy(false)}}
 if(!done&&!authReady)return <main className="orderPage"><div className="orderWrap"><section className="orderCard" style={{maxWidth:760,margin:"0 auto"}}><span className="kicker">THE PLUG MEMBERS</span><h1>Checking your member session…</h1><p>One moment while we securely check your account.</p></section></div></main>;
 if(!done&&(!user||user.isAnonymous))return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">P</span><span>THE PLUG</span></Link><Link href="/" className="button buttonLight">Back to The Plug</Link></div><section className="orderCard" style={{maxWidth:760,margin:"0 auto"}}><span className="kicker">THE PLUG MEMBERS</span><h1>Your request deserves a home.</h1><p>Join with Google to send and track sourcing requests, keep your conversations with Frank private, and receive member updates and offers in one place.</p><div className="requestBand"><strong>What membership unlocks</strong><p>🔒 Private conversations and announcement replies</p><p>📦 Request history and sourcing progress</p><p>🔔 Optional notification setup and testing</p><p>🎟️ Published member offers and recorded rewards</p></div><div className="actions"><Link href={"/account?next="+encodeURIComponent(nextPath)} className="button buttonPrimary">Continue with Google →</Link><a href="https://wa.me/c/26776411150" className="button buttonLight">Browse WhatsApp catalogue</a></div><p className="orderTruth">You can browse the public WhatsApp catalogue without joining. The Plug member tools require an account.</p></section></div></main>;
 if(done)return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">P</span><span>THE PLUG</span></Link></div><section className="orderCard" style={{maxWidth:760,margin:"0 auto"}}><span className="kicker">Request received</span><h1>Frank has your request.</h1><p className="orderTruth">Your sourcing request is recorded. It is not a quote, stock confirmation or purchase yet.</p><div className="actions"><Link href="/account" className="button buttonPrimary">Track my request</Link><a href="https://wa.me/26776411150" className="button buttonLight">WhatsApp Frank</a></div></section></div></main>;
 return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">P</span><span>THE PLUG</span></Link><Link href="/account" className="button buttonLight">My orders</Link></div><section className="orderCard" style={{maxWidth:900,margin:"0 auto"}}><div className="accountHero"><div><span className="kicker">Sourcing request</span><h1>Send Frank the item.</h1><p>If it is not in the catalogue, that is fine. Send the product name or a screenshot, then tell us your size and colour preference.</p></div><span className="accountStatus">Member request</span></div><form className="adminForm" onSubmit={submit}><label>Product or link<input value={product} onChange={e=>setProduct(e.target.value)} placeholder="e.g. Nike Blazer Mid '77 or paste a product link" required/></label><div className="fieldGrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label><label>WhatsApp / phone<input value={phone} onChange={e=>setPhone(e.target.value)} type="tel" autoComplete="tel" required/></label><label>Size<input value={size} onChange={e=>setSize(e.target.value)} placeholder="e.g. UK 9 / L"/></label><label>Colour<input value={color} onChange={e=>setColor(e.target.value)} placeholder="e.g. Black / Red"/></label></div><label>Screenshot / product image <span>(optional)</span><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<small>{file.name} selected</small>}</label><label>Anything Frank should know <span>(optional)</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} placeholder="Brand, model, budget, urgency, preferred source, etc."/></label>{message&&<p className="notice" role="alert">{message}</p>}<div className="requestBand"><strong>Before you pay</strong><p>The Plug normally works on a 50% deposit after the current quote and sourcing expectation have been confirmed. This request does not charge you or confirm stock.</p></div><button className="button buttonPrimary" type="submit" disabled={busy}>{busy?"Sending request…":"Send sourcing request"}</button></form></section></div></main>}