"use client";
import Link from "next/link";
import {GoogleAuthProvider,browserLocalPersistence,linkWithPopup,onAuthStateChanged,setPersistence,signInWithPopup,signOut,type User} from "firebase/auth";
import {useEffect,useState} from "react";
import {auth} from "@/lib/firebase/client";
import NotificationSettings from "@/components/NotificationSettings";
import CustomerConversations from "@/components/CustomerConversations";
import {getCustomerOrders,getCustomerProfile,isAdminUser,saveCustomerProfile,subscribeToCustomerOrders,type CustomerProfile,type FoodOrder} from "@/lib/firebase/data";
function statusLabel(status:string){return status==="New"?"Received":status}
function authMessage(error:unknown){const code=typeof error==="object"&&error&&"code" in error?String((error as {code?:unknown}).code):"";if(code==="auth/popup-closed-by-user")return "Google sign-in was cancelled.";if(code==="auth/popup-blocked")return "Your browser blocked the Google sign-in window. Allow pop-ups for The Plug and try again.";if(code==="auth/account-exists-with-different-credential")return "That Google email already has a The Plug account with another sign-in method. Use the original sign-in method, then connect Google from My The Plug.";if(code==="auth/credential-already-in-use")return "That Google account is already connected to another The Plug account.";if(code==="auth/provider-already-linked")return "Google is already connected to this The Plug account.";if(code==="auth/unauthorized-domain")return "Google sign-in is not available from this website yet. Please contact The Plug.";return error instanceof Error?error.message:"Google sign-in could not be completed."}
export default function AccountPage(){
 const[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<CustomerProfile|null>(null),[orders,setOrders]=useState<FoodOrder[]>([]),[busy,setBusy]=useState(false),[authReady,setAuthReady]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let stopOrders=()=>{};void setPersistence(auth,browserLocalPersistence).catch(error=>console.warn("The Plug auth persistence setup failed",error));const stopAuth=onAuthStateChanged(auth,async next=>{if(next&&await isAdminUser(next.uid)){await signOut(auth);setUser(null);setProfile(null);setOrders([]);stopOrders();stopOrders=()=>{};return}setUser(next);stopOrders();stopOrders=()=>{};if(next){try{const saved=await getCustomerProfile(next.uid);setProfile(saved??{uid:next.uid,name:next.displayName??"",email:next.email??"",phone:"",preferredDeliveryLocation:"",notes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});stopOrders=subscribeToCustomerOrders(next.uid,setOrders,error=>console.warn("The Plug customer feed unavailable",error))}catch(error){console.warn("The Plug customer data unavailable",error);setProfile({uid:next.uid,name:next.displayName??"",email:next.email??"",phone:"",preferredDeliveryLocation:"",notes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}}else{setProfile(null);setOrders([])}setAuthReady(true)});return()=>{stopOrders();stopAuth()}},[]);
 async function google(){if(!authReady||busy)return;setBusy(true);setMessage("");try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});if(user?.isAnonymous){const linked=await linkWithPopup(user,provider);const now=new Date().toISOString();const saved=await getCustomerProfile(linked.user.uid);if(!saved){const nextProfile={uid:linked.user.uid,name:linked.user.displayName??"",email:linked.user.email??"",phone:"",preferredDeliveryLocation:"",notes:"",createdAt:now,updatedAt:now};await saveCustomerProfile(nextProfile);setProfile(nextProfile)}}else if(!user){const result=await signInWithPopup(auth,provider);const now=new Date().toISOString();const saved=await getCustomerProfile(result.user.uid);if(saved)setProfile(saved);else{const nextProfile={uid:result.user.uid,name:result.user.displayName??"",email:result.user.email??"",phone:"",preferredDeliveryLocation:"",notes:"",createdAt:now,updatedAt:now};await saveCustomerProfile(nextProfile);setProfile(nextProfile)}}setMessage("Your The Plug account is connected. Your order history stays with this account.")}catch(error){setMessage(authMessage(error))}finally{setBusy(false)}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!user||!profile)return;setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const next={...profile,name:String(form.get("name")??"").trim(),email:String(form.get("email")??"").trim(),phone:String(form.get("phone")??"").trim(),preferredDeliveryLocation:String(form.get("preferredDeliveryLocation")??"").trim(),notes:String(form.get("notes")??"").trim(),updatedAt:new Date().toISOString()};try{await saveCustomerProfile(next);setProfile(next);setMessage("Your The Plug details are saved.");setOrders(await getCustomerOrders(user.uid))}catch{setMessage("We could not save your details. Please try again.")}finally{setBusy(false)}}
 return <main className="orderPage"><div className="orderWrap"><div className="orderHeader"><Link href="/" className="logo"><span className="logoMark">B</span><span>The Plug</span></Link><Link href="/order" className="button buttonLight">Request / order</Link></div><section className="orderCard accountHome" style={{maxWidth:920,margin:"0 auto"}}><div className="accountHero"><div><span className="kicker">My The Plug</span><h1>Your The Plug.</h1><p>Orders, requests and conversations — all in one place.</p></div>{user&&profile&&<span className="accountStatus">{user.isAnonymous?"Guest account":"Connected account"}</span>}</div>

{!user&&<section className="accountConnect accountConnectPrimary"><div><strong>Keep your The Plug history with you.</strong><p>Order as a guest now, or connect Google when you want saved history and faster repeat ordering.</p></div><button className="googleSignInButton" type="button" onClick={()=>void google()} disabled={busy||!authReady} aria-label="Continue with Google"><svg className="googleSignInMark" viewBox="0 0 48 48" aria-hidden="true"><path fill="#FFC107" d="M43.6 20.5H42V20H24v8h11.3C33.7 32.7 29.3 36 24 36c-6.6 0-12-5.4-12-12S17.4 12 24 12c3.1 0 5.9 1.1 8.1 3l5.7-5.7C34.3 6.1 29.5 4 24 4 12.9 4 4 12.9 4 24s8.9 20 20 20 20-8.9 20-20c0-1.2-.1-2.4-.4-3.5z"/><path fill="#FF3D00" d="M6.3 14.7l6.6 4.8C14.7 16 18.9 12 24 12c3.1 0 5.9 1.1 8.1 3l5.7-5.7C34.3 6.1 29.5 4 24 4 16.3 4 9.6 8.3 6.3 14.7z"/><path fill="#4CAF50" d="M24 44c5.4 0 10.2-2.1 13.7-5.5l-6.3-5.2C29.7 35.1 27 36 24 36c-5.2 0-9.5-3.4-11.1-8l-6.5 5C9.6 39.6 16.3 44 24 44z"/><path fill="#1976D2" d="M43.6 20.5H42V20H24v8h11.3c-1.1 3.1-3.6 5.5-6.9 6.9l6.3 5.2C34.1 41.3 44 36 44 24c0-1.2-.1-2.4-.4-3.5z"/></svg><span>{!authReady?"Checking your The Plug session…":busy?"Connecting…":"Continue with Google"}</span></button></section>}

{user&&profile&&<><p className="accountIntro">{user.isAnonymous?"Guest account · same device":"Google account connected"} · {profile.email||"Add your email in Your details"}</p>
{(() => {const active=orders.find(order=>!["Collected","Delivered","Cancelled"].includes(order.status)); return active ? <section className="accountAttention"><div><span className="kicker">Needs attention</span><h2>{active.status==="New"?"Order received":"Your order is "+statusLabel(active.status).toLowerCase()+"."}</h2><p>{active.items.map(item=>item.quantity+"× "+item.name).join(" · ")} · P{active.total.toFixed(2)}</p><small>{active.mode==="delivery"?"Delivery":"Pickup"} · {new Date(active.scheduledFor).toLocaleString()}</small></div><Link className="button buttonPrimary" href={"/orders/"+active.id}>Track order</Link></section> : null})()}

<CustomerConversations/>

<section className="accountSection boemoFeed"><div className="panelHeading"><div><span className="kicker">Activity</span><h2>What&apos;s happening.</h2></div><Link href="/order" className="textLink">Request / order →</Link></div>
<div className="feedSummary"><article><strong>{orders.length}</strong><small>Total orders</small></article><article><strong>{orders.filter(order=>order.status==="Collected"||order.status==="Delivered").length}</strong><small>Completed</small></article><article><strong>{orders.filter(order=>!["Collected","Delivered","Cancelled"].includes(order.status)).length}</strong><small>Active</small></article></div>
{orders.length===0?<article className="feedEmpty"><strong>Your The Plug story starts with your first order.</strong><p>Place an order and this space will keep the important moments together.</p><Link className="button buttonPrimary" href="/order">Order your first product</Link></article>:<div className="feedList">{orders.slice(0,6).map(order=>{const completed=order.status==="Collected"||order.status==="Delivered";const cancelled=order.status==="Cancelled";const label=completed?"Order completed":cancelled?"Order cancelled":order.status==="New"?"Order received":"Order "+statusLabel(order.status);return <article className="feedItem" key={order.id}><div className="feedMarker">{completed?"✓":cancelled?"×":"•"}</div><div className="feedBody"><div className="feedTop"><strong>{label}</strong><small>{new Date(order.createdAt).toLocaleString()}</small></div><p>{order.items.map(item=>item.quantity+"× "+item.name).join(" · ")} · P{order.total.toFixed(2)}</p><div className="feedActions"><span>{order.mode==="delivery"?"Delivery":"Pickup"} · {new Date(order.scheduledFor).toLocaleString()}</span><Link className="button buttonLight" href={"/orders/"+order.id}>{completed?"View order":"Track order"}</Link></div></div></article>})}</div>}
{orders.length>0&&<div className="feedNext"><div><span className="kicker">Order again</span><strong>Ready for another The Plug product?</strong><small>Your previous orders stay here for reference. Start a fresh order whenever you&apos;re ready.</small></div><Link className="button buttonPrimary" href="/order">Request / order</Link></div>}
</section>

<details className="accountDetails"><summary><span><strong>Your details</strong><small>Saved name, phone, delivery location and notes</small></span><b>Edit</b></summary><form className="adminForm" onSubmit={save}><label>Name<input name="name" defaultValue={profile.name} autoComplete="name" required/></label><label>Email<input name="email" type="email" defaultValue={profile.email} autoComplete="email" readOnly={Boolean(user.email)} required/></label><label>WhatsApp / phone<input name="phone" type="tel" defaultValue={profile.phone} autoComplete="tel" required/></label><label>Preferred delivery location <span>(optional)</span><input name="preferredDeliveryLocation" defaultValue={profile.preferredDeliveryLocation}/></label><label>Notes <span>(optional)</span><textarea name="notes" defaultValue={profile.notes}/></label><button className="button buttonPrimary" type="submit" disabled={busy}>{busy?"Saving…":"Save my The Plug details"}</button></form></details>

<section className="accountSection" id="notifications"><div className="panelHeading"><div><span className="kicker">Preferences</span><h2>Notifications.</h2></div></div><NotificationSettings/></section>

<section className="accountBenefits accountSection"><div className="panelHeading"><div><span className="kicker">Member</span><h2>Useful extras.</h2></div></div><p>Connected customers may become eligible for owner-controlled offers, early access or priority handling when The Plug runs them.</p><div className="benefitGrid"><article><strong>🎁 Member offers</strong><small>Selected discounts or specials when the business chooses to run them.</small></article><article><strong>⚡ Earlier requests</strong><small>Advance requests may receive priority handling, subject to business capacity.</small></article><article><strong>🍽️ Catering planning</strong><small>An established account can help The Plug recognize you when planning larger requests.</small></article></div><p className="orderTruth">These are potential benefits, not guarantees. The business controls each offer, request and availability.</p></section>
</>}

{message&&<p className="notice" role="status">{message}</p>}{user&&<div className="accountBottomActions"><button className="button buttonLight" type="button" onClick={()=>void signOut(auth)}>Sign out</button><span className="orderTruth">Guest ordering never requires authentication.</span></div>}<p className="accountFooterNote orderTruth">Your The Plug account keeps your order history private to this customer account/device. Connecting Google later does not replace your existing guest identity or order history.</p></section></div></main>;
}
